version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tfshim
    goos:
      - linux
    goarch:
      - amd64

archives:
  - formats:
      - binary
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
